# Generated by Django 3.0.3 on 2020-05-14 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsender',
            name='delay',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(86400)], verbose_name='Задержка'),
        ),
        migrations.AlterField(
            model_name='emailsender',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='emailsender',
            name='message',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='emailsender',
            name='send_status',
            field=models.SmallIntegerField(choices=[(1, 'Ожидание'), (2, 'Отправлено'), (3, 'Ошибка')], default=1, verbose_name='Статус отправки'),
        ),
        migrations.AlterField(
            model_name='emailsender',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Тема'),
        ),
    ]
